# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58497859d5a97a9c7637024fdd096792f34ed4e6875791091ee526f0591133ec6da712ba001f5b278c892beea1336814d22459b1a155d0f1e7a76c3681a5870d

test:
  secret_key_base: 64a850a00f4b89229f5ff63f43bcacb3e63b267091c8bc40ad417487807174dcf9087203185ac551aa9bc13a4d539de2f4aaa7a3bb13568da274be3a8de0eeee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
